services:
    mysql:
        image: mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: snippetbox
            MYSQL_USER: web
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: rootpass
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
